### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by mrsweaters** [y-js/y-websocket#2]
I'm getting the following two errors in a fresh project created with `vue-cli`:

```
 warning  in ./node_modules/y-prosemirror/src/plugins/sync-plugin.js

"export 'Item' (imported as 'Y') was not found in 'yjs'

 warning  in ./node_modules/y-prosemirror/src/plugins/undo-plugin.js

"export 'UndoManager' was not found in 'yjs'
```

**Comment by dmonad** [comment]
Please always include versions and how to reproduce this error. I'm not familiar with the vue build system. But if you describe how to reproduce I might find out how to fix it
