### ISSUE TITLE
Cannot resolve dependency 'yjs/provider/websocket.js'

### ISSUE THREAD

**Issue by crapthings** [y-js/y-websocket#4]
import { WebsocketProvider } from 'yjs/provider/websocket.js'

![image](https://user-images.githubusercontent.com/1147704/63905803-f5fd0780-ca47-11e9-8e93-af5bbdddccd1.png)

i've cloned this module, and copy the code from readme, but it seems   there's no yjs/provider

**Comment by crapthings** [comment]
if i use cloned module
import { WebsocketProvider } from '../../../y-websocket'

```
y-websocket.js:167 Uncaught TypeError: Class constructor Observable cannot be invoked without 'new'
    at new WebsocketProvider (y-websocket.js:167)
    at index.js:13
```

**Comment by dmonad** [comment]
Correct. There is no `yjs/provider`. Where did you find this? 

```js
import { WebsocketProvider } from 'yjs/provider/websocket.js'
```

It definitely is not in the readme https://github.com/y-js/yjs/blob/master/README.v13.md

For the most up-to-date versions you can also look at https://github.com/y-js/yjs-demos

**Comment by crapthings** [comment]
![image](https://user-images.githubusercontent.com/1147704/63943808-f5458f00-caa2-11e9-86eb-5afbfb502962.png)
